### ISSUE TITLE
更新后启动报错

### ISSUE THREAD

**Issue by williamfang** [lrzjason/T2ITrainer#4]
Loaded configuration from config.json
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "D:\AI\T2ITrainer\venv\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "D:\AI\T2ITrainer\venv\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\AI\T2ITrainer\venv\lib\site-packages\gradio\blocks.py", line 1897, in process_api
    result = await self.call_function(
  File "D:\AI\T2ITrainer\venv\lib\site-packages\gradio\blocks.py", line 1483, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\AI\T2ITrainer\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\AI\T2ITrainer\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "D:\AI\T2ITrainer\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "D:\AI\T2ITrainer\venv\lib\site-packages\gradio\utils.py", line 816, in wrapper
    response = f(*args, **kwargs)
TypeError: run() takes 30 positional arguments but 31 were given

**Comment by lrzjason** [comment]
再更新一下，现在的版本还没稳定，持续更新中

**Comment by williamfang** [comment]
> 再更新一下，现在的版本还没稳定，持续更新中

回退了gradio version 4.29.0 -> 4.26.0，问题解决
